server:
    port: 8080
mybatis:
#    mapper-locations: classpath:mappers/*.xml
    mapper-locations: classpath:com/dalefe/generator/mappers/*.xml
spring:
    application: dalefe
    datasource:
        url: jdbc:mysql://localhost:3306/test?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver